config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  root 'welcome#index'


  get 'welcome/index'



  # get 'profile/profile' => 'profile#profile'
  # get 'profile/user_data' => 'profile#user_data'
  # get 'profile' => 'profile#show'
  # post 'profile' => 'profile#create'


end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "LED Exhibit Lighting" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>


  <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><a href="#">LED Exhibit Lighting</a></h1>
        </li>
        <li class="toggle-topbar menu-icon">
          <a href="#"><span>menu</span></a>
        </li>
      </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
        <li>
          <%= link_to "Login", new_model_session_path, :class => 'navbar-link' %>
        </li>
      <li class="divider"></li>
      <li>
        <li><%= link_to "Sign up", new_model_registration_path, :class => 'navbar-link' %></li>
      </li>
      <li class="divider"></li>
      <li>
        <li><%= link_to "Logout", destroy_model_session_path, method: :delete, :class => 'navbar-link' %></li>
      </li>
    </ul>
  </section>

   <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="has-dropdown">
        <a href="#">Products</a>
        <ul class="dropdown">
          <li><a href="#">Display Armlights</a></li>
          <li><a href="#">Telescopic Lightstands </a></li>
          <li><a href="#">System Tracklights</a></li>
          <!-- <li class="active"><a href="#">Active link in dropdown</a></li> -->
        </ul>
      </li>
    </ul>
  </nav>


    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>